### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by timydaley** [kundajelab/simdna#9]
Hi,
I'm trying to use the simdna package to generate test data for motifs, but I find that the package is very sparse in documentation.  The particular questions I have are as follows
I want to generate sequences with a random insertion of a single motif.  The script to do this is motifGrammarSimulation.py, right?
For the arguments of motifGrammarSimulation.py:
What is the format of pathToMotifs?
What are the motif names?  Should these be in the pathToMotifs file?
What does the flag --bestHit mean?
What are the different generation settings?
What are acceptable arguments to --fixedSpacingOrMinSpacing?  What do fixed spacing, min spacing, and max spacing mean?

I apologize if this information is available somewhere.  If you could point me in that direction, that would be very helpful.  Thank you.

**Comment by AvantiShri** [comment]
Hi Tim,

Perfectly valid questions and no I haven’t gotten around to documenting things.

motifGrammarSimulation is actually meant for simulating grammars between two motifs, which is why all the arguments about generation settings, “fixed spacing”, “min spacing”, etc are there (these affect the spacing between the motifs). If all you care about is instances of a single motif, then I recommend the script densityMotifSimulation with max-motifs, min-motifs and mean-motifs set to 1. This will force every sequence to contain exactly one motif instance. You can see example arguments here: https://github.com/kundajelab/simdna/blob/master/scripts_test/test_density_motif_simulation_script.sh

For pathToMotifs, if you are ok with using the ENCODE motifs, you can leave this blank and it will automatically use the file at https://github.com/kundajelab/simdna/tree/master/simdna/resources/encode_motifs.txt.gz. Otherwise, you can specify a regular file path.

motifNames are indeed names of motifs in the pathToMotifs file. For the ENCODE motifs, you can get a list of the motif names at compbio.mit.edu/encode-motifs/.

The bestHit flag will use only the very strongest possible match to the motif (i.e. it won’t sample from the PWM - it will just put the strongest hit in). Good for debugging purposes, but not very realistic.

Please let me know if you have any other questions.

**Comment by timydaley** [comment]
Thank you so much for the quick response Avanti.  I greatly appreciate it.  I think this should be enough to get me started.  If I have any more questions, and hopefully I won't, I will contact you.
Thank you!

**Comment by timydaley** [comment]
Sorry to bother you Avanti.  The file encode_motifs.txt.gz at https://github.com/kundajelab/simdna/blob/master/simdna/resources/encode_motifs.txt.gz is not in gzip format 
$ gunzip simdna/encode_motifs.txt.gz 
gunzip: simdna/encode_motifs.txt.gz: not in gzip format
What is the format?

**Comment by AvantiShri** [comment]
Hi @timydaley,

It's in the "resources" subdirectory - see screenshot below:

<img width="410" alt="Screen Shot 2019-03-27 at 4 14 10 PM" src="https://user-images.githubusercontent.com/2302598/55118406-6e335b80-50ab-11e9-83f6-8df15b01d89f.png">

I have a colab notebook running the code above at https://gist.github.com/AvantiShri/c32ef19dceae4698c4cb2b9b10a31f64.

**Comment by timydaley** [comment]
Oh.  I know what I did wrong.  I'm dumb.  I downloaded the html page.  
https://tenor.com/tMir.gif

**Comment by AvantiShri** [comment]
no worries :-)
